import type { EventRecord } from "./types";

/**
 * Seed events. The store (`lib/store.tsx`) loads these on first run and then
 * persists any changes to localStorage. Replace this with an API fetch later.
 *
 * All data here is fake/placeholder for demo purposes — generic company and
 * person names, sample venues, and round placeholder numbers. Several events
 * are intentionally clustered in July 2026 so the calendar view shows activity.
 */
export const SEED_EVENTS: EventRecord[] = [
  {
    id: "evt-1001",
    eventName: "Acme Corporation Annual Gala",
    status: "Confirmed",
    createdAt: "2026-05-20T09:00:00.000Z",
    updatedAt: "2026-06-18T03:00:00.000Z",
    client: {
      clientName: "Acme Corporation",
      contactPerson: "John Smith",
      mobile: "0917 000 0001",
      email: "john.smith@example.com",
    },
    event: {
      eventType: "Corporate Event",
      serviceStyle: "Buffet",
      eventDate: "2026-07-02",
      eventTime: "6:00 PM",
      venue: "Grand Ballroom, Sample Hotel",
      venueAddress: "123 Sample Street, Sample City",
      pax: 200,
    },
    commercial: {
      packageTier: "Gold",
      packageName: "Gold Package",
      budgetPerHead: 1500,
      menu: [
        { category: "Appetizer", name: "Garden Salad" },
        { category: "Soup", name: "Cream of Mushroom Soup" },
        { category: "Main", name: "Roast Chicken" },
        { category: "Main", name: "Beef Stroganoff" },
        { category: "Dessert", name: "Fruit Platter" },
        { category: "Beverage", name: "Iced Tea" },
      ],
      addOns: [
        { name: "Coffee Station", price: 5000 },
        { name: "Lights & Sounds", price: 20000 },
      ],
      transportationFee: 5000,
      discount: 0,
      specialRequests: "Sample request: vegetarian option for 20 guests.",
    },
    order: {
      theme: "Sample Theme — Corporate",
      setupRequirements: "Sample setup: stage, 20 round tables, registration area.",
      ingress: "2:00 PM",
      egress: "11:00 PM",
      operationalNotes: "Placeholder operational note.",
      staffNotes: "Placeholder staff note.",
    },
    reservationFee: 30000,
  },
  {
    id: "evt-1002",
    eventName: "Globex Product Launch",
    status: "Quotation Sent",
    createdAt: "2026-06-01T05:00:00.000Z",
    updatedAt: "2026-06-20T08:00:00.000Z",
    client: {
      clientName: "Globex Corporation",
      contactPerson: "Jane Doe",
      mobile: "0917 000 0002",
      email: "jane.doe@example.com",
    },
    event: {
      eventType: "Product Launch & Cocktails",
      serviceStyle: "Cocktail / Canapés",
      eventDate: "2026-07-04",
      eventTime: "7:00 PM",
      venue: "Function Room A",
      venueAddress: "456 Placeholder Ave, Sample City",
      pax: 120,
    },
    commercial: {
      packageTier: "Gold",
      packageName: "Gold Package",
      budgetPerHead: 1600,
      menu: [
        { category: "Canapé", name: "Sample Canapé 1" },
        { category: "Canapé", name: "Sample Canapé 2" },
        { category: "Station", name: "Cheese & Crackers" },
        { category: "Dessert", name: "Mini Desserts" },
        { category: "Beverage", name: "Mocktail Bar" },
      ],
      addOns: [
        { name: "Mobile Bar", price: 15000 },
        { name: "Photo Booth", price: 12000 },
      ],
      transportationFee: 5000,
      discount: 0,
      specialRequests: "Sample request: roving service only, no seated tables.",
    },
    order: {
      theme: "Sample Theme — Modern",
      setupRequirements: "Sample setup: cocktail tables, product display.",
      ingress: "3:00 PM",
      egress: "11:00 PM",
      operationalNotes: "Placeholder operational note.",
      staffNotes: "Placeholder staff note.",
    },
    reservationFee: 20000,
  },
  {
    id: "evt-1003",
    eventName: "Smith–Doe Wedding",
    status: "Upcoming",
    createdAt: "2026-04-10T01:00:00.000Z",
    updatedAt: "2026-06-19T08:00:00.000Z",
    client: {
      clientName: "Jane Doe",
      contactPerson: "Jane Doe",
      mobile: "0917 000 0003",
      email: "jane.wedding@example.com",
    },
    event: {
      eventType: "Wedding Reception",
      serviceStyle: "Plated / Sit-down",
      eventDate: "2026-07-09",
      eventTime: "5:00 PM",
      venue: "Garden Pavilion",
      venueAddress: "789 Example Road, Sample City",
      pax: 150,
    },
    commercial: {
      packageTier: "Platinum",
      packageName: "Platinum Package",
      budgetPerHead: 2000,
      menu: [
        { category: "Appetizer", name: "Sample Appetizer" },
        { category: "Soup", name: "Pumpkin Soup" },
        { category: "Main", name: "Grilled Salmon" },
        { category: "Main", name: "Beef Tenderloin" },
        { category: "Dessert", name: "Sample Dessert" },
        { category: "Beverage", name: "Juice & Soda" },
      ],
      addOns: [
        { name: "Dessert Station", price: 8000 },
        { name: "Lights & Sounds", price: 20000 },
      ],
      transportationFee: 8000,
      discount: 10000,
      specialRequests: "Sample request: pastel theme, first dance at 7 PM.",
    },
    order: {
      theme: "Sample Theme — Garden",
      setupRequirements: "Sample setup: 15 round tables, couple's table, aisle.",
      ingress: "1:00 PM",
      egress: "11:00 PM",
      operationalNotes: "Placeholder operational note.",
      staffNotes: "Placeholder staff note.",
    },
    reservationFee: 30000,
  },
  {
    id: "evt-1004",
    eventName: "Initech Team Building",
    status: "Draft",
    createdAt: "2026-06-15T14:00:00.000Z",
    updatedAt: "2026-06-22T02:00:00.000Z",
    client: {
      clientName: "Initech",
      contactPerson: "Robert Johnson",
      mobile: "0917 000 0004",
      email: "robert.johnson@example.com",
    },
    event: {
      eventType: "Corporate Event",
      serviceStyle: "Buffet",
      eventDate: "2026-07-16",
      eventTime: "12:00 NN",
      venue: "Conference Center",
      venueAddress: "321 Demo Blvd, Sample City",
      pax: 80,
    },
    commercial: {
      packageTier: "Silver",
      packageName: "Silver Package",
      budgetPerHead: 850,
      menu: [
        { category: "Appetizer", name: "House Salad" },
        { category: "Main", name: "Fried Chicken" },
        { category: "Main", name: "Pork Stew" },
        { category: "Main", name: "Steamed Rice" },
        { category: "Dessert", name: "Sliced Fruits" },
      ],
      addOns: [{ name: "Extra Waiters", price: 3000 }],
      transportationFee: 5000,
      discount: 0,
      specialRequests: "Sample request: buffet to be ready by 11:30 AM.",
    },
    order: {
      theme: "Sample Theme — Casual",
      setupRequirements: "Sample setup: long tables, buffet line.",
      ingress: "9:00 AM",
      egress: "4:00 PM",
      operationalNotes: "Placeholder operational note.",
      staffNotes: "Placeholder staff note.",
    },
    reservationFee: 10000,
  },
  {
    id: "evt-1005",
    eventName: "Sample 18th Birthday",
    status: "Draft",
    createdAt: "2026-06-10T14:00:00.000Z",
    updatedAt: "2026-06-23T02:00:00.000Z",
    client: {
      clientName: "Maria Cruz",
      contactPerson: "Maria Cruz",
      mobile: "0917 000 0005",
      email: "maria.cruz@example.com",
    },
    event: {
      eventType: "18th Birthday Debut",
      serviceStyle: "Buffet",
      eventDate: "2026-07-18",
      eventTime: "6:30 PM",
      venue: "Events Place",
      venueAddress: "654 Sample Lane, Sample City",
      pax: 100,
    },
    commercial: {
      packageTier: "Gold",
      packageName: "Gold Package",
      budgetPerHead: 1200,
      menu: [
        { category: "Appetizer", name: "Garden Salad" },
        { category: "Main", name: "Baked Chicken" },
        { category: "Main", name: "Beef Caldereta" },
        { category: "Main", name: "Seafood Pasta" },
        { category: "Dessert", name: "Dessert Bar" },
      ],
      addOns: [
        { name: "Photo Booth", price: 12000 },
        { name: "Dessert Station", price: 8000 },
      ],
      transportationFee: 5000,
      discount: 0,
      specialRequests: "Sample request: rose gold theme, dance floor at center.",
    },
    order: {
      theme: "Sample Theme — Rose Gold",
      setupRequirements: "Sample setup: 10 round tables, stage, dance floor.",
      ingress: "2:30 PM",
      egress: "11:00 PM",
      operationalNotes: "Placeholder operational note.",
      staffNotes: "Placeholder staff note.",
    },
    reservationFee: 15000,
  },
  {
    id: "evt-1006",
    eventName: "Umbrella Corp Conference",
    status: "Confirmed",
    createdAt: "2026-05-05T02:00:00.000Z",
    updatedAt: "2026-06-17T05:00:00.000Z",
    client: {
      clientName: "Umbrella Corporation",
      contactPerson: "Alex Lee",
      mobile: "0917 000 0006",
      email: "alex.lee@example.com",
    },
    event: {
      eventType: "Conference / Seminar Buffet",
      serviceStyle: "Buffet",
      eventDate: "2026-07-25",
      eventTime: "8:00 AM",
      venue: "Convention Hall",
      venueAddress: "987 Example Drive, Sample City",
      pax: 300,
    },
    commercial: {
      packageTier: "Silver",
      packageName: "Silver Package",
      budgetPerHead: 950,
      menu: [
        { category: "AM Snack", name: "Sandwich & Coffee" },
        { category: "Lunch", name: "Chicken Curry" },
        { category: "Lunch", name: "Pork Adobo" },
        { category: "Lunch", name: "Steamed Rice" },
        { category: "PM Snack", name: "Pastry & Juice" },
      ],
      addOns: [{ name: "Coffee Station", price: 5000 }],
      transportationFee: 8000,
      discount: 15000,
      specialRequests: "Sample request: strict 10 AM and 3 PM snack timing.",
    },
    order: {
      theme: "Sample Theme — Formal",
      setupRequirements: "Sample setup: theater seating, 2 buffet lines.",
      ingress: "5:00 AM",
      egress: "6:00 PM",
      operationalNotes: "Placeholder operational note.",
      staffNotes: "Placeholder staff note.",
    },
    reservationFee: 40000,
  },
  {
    id: "evt-1007",
    eventName: "Stark Industries Anniversary",
    status: "Quotation Sent",
    createdAt: "2026-06-05T07:00:00.000Z",
    updatedAt: "2026-06-21T05:00:00.000Z",
    client: {
      clientName: "Stark Industries",
      contactPerson: "Chris Tan",
      mobile: "0917 000 0007",
      email: "chris.tan@example.com",
    },
    event: {
      eventType: "Anniversary Celebration",
      serviceStyle: "Plated / Sit-down",
      eventDate: "2026-08-08",
      eventTime: "6:00 PM",
      venue: "Rooftop Venue",
      venueAddress: "111 Sample Heights, Sample City",
      pax: 180,
    },
    commercial: {
      packageTier: "Platinum",
      packageName: "Platinum Package",
      budgetPerHead: 2200,
      menu: [
        { category: "Appetizer", name: "Sample Appetizer" },
        { category: "Soup", name: "Lobster Bisque" },
        { category: "Main", name: "Braised Short Rib" },
        { category: "Dessert", name: "Chocolate Cake" },
        { category: "Beverage", name: "Wine & Juice" },
      ],
      addOns: [
        { name: "Mobile Bar", price: 15000 },
        { name: "Lights & Sounds", price: 20000 },
      ],
      transportationFee: 8000,
      discount: 0,
      specialRequests: "Sample request: black-tie program, reserved head table.",
    },
    order: {
      theme: "Sample Theme — Elegant",
      setupRequirements: "Sample setup: 18 round tables, stage, AV.",
      ingress: "12:00 PM",
      egress: "12:00 AM",
      operationalNotes: "Placeholder operational note.",
      staffNotes: "Placeholder staff note.",
    },
    reservationFee: 40000,
  },
  {
    id: "evt-1008",
    eventName: "Hooli Mid-Year Party",
    status: "Completed",
    createdAt: "2026-04-25T09:00:00.000Z",
    updatedAt: "2026-06-13T09:00:00.000Z",
    client: {
      clientName: "Hooli Inc.",
      contactPerson: "Sam Reyes",
      mobile: "0917 000 0008",
      email: "sam.reyes@example.com",
    },
    event: {
      eventType: "Corporate Event",
      serviceStyle: "Buffet",
      eventDate: "2026-06-12",
      eventTime: "6:00 PM",
      venue: "Function Hall B",
      venueAddress: "222 Placeholder St, Sample City",
      pax: 150,
    },
    commercial: {
      packageTier: "Gold",
      packageName: "Gold Package",
      budgetPerHead: 1300,
      menu: [
        { category: "Appetizer", name: "Garden Salad" },
        { category: "Main", name: "Roast Beef" },
        { category: "Main", name: "Grilled Fish" },
        { category: "Main", name: "Steamed Rice" },
        { category: "Dessert", name: "Sliced Fruits" },
      ],
      addOns: [{ name: "Coffee Station", price: 5000 }],
      transportationFee: 5000,
      discount: 0,
      specialRequests: "Sample request: program ends 10 PM.",
    },
    order: {
      theme: "Sample Theme — Corporate",
      setupRequirements: "Sample setup: 15 round tables, buffet line.",
      ingress: "2:00 PM",
      egress: "11:00 PM",
      operationalNotes: "Placeholder operational note.",
      staffNotes: "Placeholder staff note.",
    },
    reservationFee: 20000,
  },
  {
    id: "evt-1009",
    eventName: "Sample Charity Gala",
    status: "Completed",
    createdAt: "2026-03-15T07:00:00.000Z",
    updatedAt: "2026-05-20T05:00:00.000Z",
    client: {
      clientName: "Sample Foundation",
      contactPerson: "Pat Garcia",
      mobile: "0917 000 0009",
      email: "pat.garcia@example.com",
    },
    event: {
      eventType: "Charity Fundraising Gala",
      serviceStyle: "Plated / Sit-down",
      eventDate: "2026-05-15",
      eventTime: "6:00 PM",
      venue: "Sample Pavilion",
      venueAddress: "333 Demo Court, Sample City",
      pax: 200,
    },
    commercial: {
      packageTier: "Platinum",
      packageName: "Platinum Package",
      budgetPerHead: 1800,
      menu: [
        { category: "Appetizer", name: "Sample Appetizer" },
        { category: "Soup", name: "Cream Soup" },
        { category: "Main", name: "Chicken Roulade" },
        { category: "Dessert", name: "Sample Dessert" },
        { category: "Beverage", name: "Juice & Soda" },
      ],
      addOns: [{ name: "Lights & Sounds", price: 20000 }],
      transportationFee: 8000,
      discount: 0,
      specialRequests: "Sample request: silent auction area, head table for 10.",
    },
    order: {
      theme: "Sample Theme — Formal",
      setupRequirements: "Sample setup: 20 round tables, gala stage.",
      ingress: "12:00 PM",
      egress: "12:00 AM",
      operationalNotes: "Placeholder operational note.",
      staffNotes: "Placeholder staff note.",
    },
    reservationFee: 50000,
  },
];
